package com.inakianduaga.models.avroCompiled;

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum filters { 
  GREYSCALE, CHROME, HALFTONE, BLUR, DIFFUSE, CONTOUR, EDGE, OIL, ROBERTS, SUMMER, TRITONE, SOLARIZE, TELEVISION, VINTAGE, INVERT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"filters\",\"namespace\":\"inakianduaga.kafkaImageProcessor\",\"symbols\":[\"GREYSCALE\",\"CHROME\",\"HALFTONE\",\"BLUR\",\"DIFFUSE\",\"CONTOUR\",\"EDGE\",\"OIL\",\"ROBERTS\",\"SUMMER\",\"TRITONE\",\"SOLARIZE\",\"TELEVISION\",\"VINTAGE\",\"INVERT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
