#
# Docker Compose to wire up all containers for local development
# https://docs.docker.com/compose/compose-file/
#
version: '2'
services:

  #===============
  # Core Services
  #===============

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  schema-registry:
    image: confluent/schema-registry
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_access_control_allow_methods: 'GET,POST,OPTIONS'
      SCHEMA_REGISTRY_access_control_allow_origin: '*'
    expose:
      - 8081
    links:
      - zookeeper
      - kafka
    depends_on:
      - kafka
      - zookeeper

  #===============
  # Applications
  #===============

  ui:
    build: ./node
    image: node
    ports:
      - 3000:3000
    links:
      - ui-backend
    volumes:
      - ../ui:/app
    environment:
      - BACKEND_ENDPOINT=localhost:9000
    entrypoint:
      - npm
      - start

  ui-backend:
    ports:
      - "9000:9000"
    build: ./sbt
    image: sbt
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ../ui-backend:/root
    environment:
      - KAFKA_ENDPOINT=kafka:9092
    entrypoint:
      - sbt
      - run
    stdin_open: true

  processor:
    ports:
      - "9000:9000"
    build: ./sbt
    image: sbt
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ../processor:/root
    environment:
      - KAFKA_ENDPOINT=kafka:9092
    entrypoint:
      - sbt
      - run
    stdin_open: true

  # =============
  # Rest proxies
  # =============

  kafka-rest-proxy:
    image: confluent/rest-proxy
    ports:
      - 8082:8082
    links:
      - zookeeper
      - kafka
      - schema-registry
    depends_on:
      - schema-registry
      - kafka
      - zookeeper

  # ================
  # Debugging UI visualization
  # ================

  schema-registry-ui:
    image: landoop/schema-registry-ui
    ports:
      - 8083:8000
    environment:
      - SCHEMAREGISTRY_URL=http://localhost:8081
    links:
      - schema-registry
    depends_on:
      - schema-registry

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    ports:
      - 8084:8000
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest-proxy:8082
      - PROXY=true
    links:
      - kafka-rest-proxy
    depends_on:
      - kafka-rest-proxy


